//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 08:28:12 PM PDT 
//


package com.viper.vome.dao;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndexClassType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IndexClassType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="unique"/&gt;
 *     &lt;enumeration value="fulltext"/&gt;
 *     &lt;enumeration value="spatial"/&gt;
 *     &lt;enumeration value="default"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IndexClassType")
@XmlEnum
public enum IndexClassType {

    @XmlEnumValue("unique")
    UNIQUE("unique"),
    @XmlEnumValue("fulltext")
    FULLTEXT("fulltext"),
    @XmlEnumValue("spatial")
    SPATIAL("spatial"),
    @XmlEnumValue("default")
    DEFAULT("default");
    private final String value;

    IndexClassType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IndexClassType fromValue(String v) {
        for (IndexClassType c: IndexClassType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
