//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.06 at 07:08:16 PM PDT 
//


package com.viper.vome.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileFormat.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FileFormat"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SQL"/&gt;
 *     &lt;enumeration value="XML"/&gt;
 *     &lt;enumeration value="CSV"/&gt;
 *     &lt;enumeration value="TEXT"/&gt;
 *     &lt;enumeration value="HTML"/&gt;
 *     &lt;enumeration value="EXCEL"/&gt;
 *     &lt;enumeration value="META"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FileFormat")
@XmlEnum
public enum FileFormat {

    SQL,
    XML,
    CSV,
    TEXT,
    HTML,
    EXCEL,
    META;

    public String value() {
        return name();
    }

    public static FileFormat fromValue(String v) {
        return valueOf(v);
    }

}
